import test from "jest-t-assert";
import xxhash from "../src";

// The test cases were taken from tests of other implementation and the
// resulting hashes have been generated by running another implementation.
// All cases used the seed 0.
const testCases = [
  { input: "", h32: "2cc5d05", h64: "ef46db3751d8e999" },
  { input: "a", h32: "550d7456", h64: "d24ec4f1a98c6e5b" },
  { input: "as", h32: "9d5a0464", h64: "1c330fb2d66be179" },
  { input: "asd", h32: "3d83552b", h64: "631c37ce72a97393" },
  { input: "asdf", h32: "5e702c32", h64: "415872f599cea71e" },
  { input: "abc", h32: "32d153ff", h64: "44bc2cf5ad770999" },
  { input: "abcd", h32: "a3643705", h64: "de0327b0d25d92cc" },
  {
    input: "Call me Ishmael. Some years ago--never mind how long precisely-",
    h32: "6f320359",
    h64: "2a2e85470d6fd96"
  },
  {
    input:
      "The quick brown fox jumps over the lazy dog http://i.imgur.com/VHQXScB.gif",
    h32: "5ce7b616",
    h64: "93267f9820452ead"
  },
  { input: "heiå", h32: "db5abccc", h64: "b9d3d990d2001a1a" },
  { input: "κόσμε", h32: "d855f606", h64: "a0488960c70d8772" }
];

for (const testCase of testCases) {
  test(`h32 of ${testCase.input}`, async t => {
    const hasher = await xxhash();
    const h32 = hasher.h32(testCase.input);
    t.is(h32, testCase.h32);
  });

  test(`h32Raw of ${testCase.input}`, async t => {
    const encoder = new TextEncoder();
    const hasher = await xxhash();
    const h32 = hasher.h32Raw(encoder.encode(testCase.input)).toString(16);
    t.is(h32, testCase.h32);
  });

  test(`h64 of ${testCase.input}`, async t => {
    const hasher = await xxhash();
    const h64 = hasher.h64(testCase.input);
    t.is(h64, testCase.h64);
  });

  test(`h64Raw of ${testCase.input}`, async t => {
    const encoder = new TextEncoder();
    const hasher = await xxhash();
    const h64uint8array = hasher.h64Raw(encoder.encode(testCase.input));
    t.is(h64uint8array.length, 8);
    const dataView = new DataView(h64uint8array.buffer);
    const h64str =
      dataView.getUint32(0, true).toString(16) +
      dataView.getUint32(4, true).toString(16);
    t.is(h64str, testCase.h64);
  });
}

test("h32 with different seeds produces different hashes", async t => {
  const hasher = await xxhash();
  const input = "different seeds";
  const h320 = hasher.h32(input, 0);
  const h32abcd = hasher.h32(input, 0xabcd);
  t.not(h320, h32abcd);
});

test("h64 with different seeds produces different hashes", async t => {
  const hasher = await xxhash();
  const input = "different seeds";
  const h640 = hasher.h64(input, 0, 0);
  const h64lowAbcd = hasher.h64(input, 0, 0xabcd);
  const h64highAbcd = hasher.h64(input, 0xabcd, 0);
  t.not(h640, h64lowAbcd);
  t.not(h640, h64highAbcd);
  t.not(h64lowAbcd, h64highAbcd);
});

test("a string greater than the initial memory size works", async t => {
  const hasher = await xxhash();
  const bytesPerPage = 64 * 1024;
  const input = "z".repeat(bytesPerPage + 1);
  const h32 = hasher.h32(input, 0);
  const h64 = hasher.h64(input, 0, 0);
  t.is(h32, "7871ee9b");
  t.is(h64, "68278ba56dc14510");
});
